DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS devices;

CREATE TABLE devices (
    device_id VARCHAR(16) PRIMARY KEY,
    device_name VARCHAR(64) NOT NULL,
    location_code VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    last_heartbeat TIMESTAMP WITH TIME ZONE NOT NULL,
    latency_ms INTEGER NOT NULL
);

CREATE TABLE orders (
    order_id VARCHAR(16) PRIMARY KEY,
    location_code VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    validated_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(16) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    location_code VARCHAR(16) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    message VARCHAR(128) NOT NULL
);

CREATE INDEX idx_events_location ON events(location_code);
CREATE INDEX idx_events_severity ON events(severity);

